# This file was generated by GoReleaser. DO NOT EDIT.
cask "acloud" do
  version "0.31.0"

  on_macos do
    on_intel do
      sha256 "6bfbbe7d217caa26b3994208b9e06be7d4b2b9edcf450beb9228230a0cac7192"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e635b6533b6ea225a330b1b5dafc7dc1b887cd21b48e391dacdc8490ee0fc1a"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "311ba8f875c509f29de4922443e158fb6cf50b4e0cf2c2adc40402b9e97b4d5b"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b4ce6019430f98672d4929e6278b1a3a3928de2d2d1a1240877f28dcfac166a"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_linux_arm64.tar.gz"
    end
  end

  name "acloud"
  desc ""
  homepage "https://docs.avisi.cloud/docs/cli/acloud/overview/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acloud"
  bash_completion "completions/acloud.bash"
  fish_completion "completions/acloud.fish"
  zsh_completion "completions/acloud.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acloud"]
    end
  end

  # No zap stanza required

end
