# This file was generated by GoReleaser. DO NOT EDIT.
cask "acloud-toolkit" do
  desc ""
  homepage "https://docs.avisi.cloud/docs/cli/acloud-toolkit/overview"
  version "1.14.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acloud-toolkit"
  bash_completion "completions/acloud-toolkit.bash"
  zsh_completion "completions/acloud-toolkit.zsh"
  fish_completion "completions/acloud-toolkit.fish"

  on_macos do
    on_intel do
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v1.14.0/acloud-toolkit_1.14.0_darwin_amd64.tar.gz"
      sha256 "3a33717e0c2a1654a1df13543ebcd03d5dc2d9a24758c9a0d98c75dc9a4d0c6c"
    end
    on_arm do
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v1.14.0/acloud-toolkit_1.14.0_darwin_arm64.tar.gz"
      sha256 "6ea336ca8af19da3e15aee6b13c1bb0038b269e1f5492fadbf7cd26da57873c3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v1.14.0/acloud-toolkit_1.14.0_linux_amd64.tar.gz"
      sha256 "8b10be3fec1bac50d194dc701bc08aaae22b56850ba0c18a80690e19cbba49ef"
    end
    on_arm do
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v1.14.0/acloud-toolkit_1.14.0_linux_arm64.tar.gz"
      sha256 "cb17b159824cd2a9c38abf7db3d3c3f0bd0fc52b5c174f395c4d41278777f2dc"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'acloud-toolkit' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acloud-toolkit"]
    end
  end

  # No zap stanza required
end
