# This file was generated by GoReleaser. DO NOT EDIT.
cask "acloud" do
  version "0.32.0"

  on_macos do
    on_intel do
      sha256 "49585374154f175643328d517a19f297d74e3efceab173b746b4c025def832b0"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d6342f26ad204d3608d70f3c5b923af5086f26f4515a04fc7d6e54166944de6"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38d58ba36130db7600b97517bcc5d487bf9425cd8cc7f6536feabc88055cb0c3"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e03916fcc0f7e03257a190d5ff3b7edbdd919f9d6218e9154978db7d31bf0bda"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_linux_arm64.tar.gz"
    end
  end

  name "acloud"
  desc ""
  homepage "https://docs.avisi.cloud/docs/cli/acloud/overview/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acloud"
  bash_completion "completions/acloud.bash"
  fish_completion "completions/acloud.fish"
  zsh_completion "completions/acloud.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acloud"]
    end
  end

  # No zap stanza required

end
