# This file was generated by GoReleaser. DO NOT EDIT.
cask "acloud" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/acloud"]
    end
  end

  version "0.34.0"

  on_macos do
    on_arm do
      sha256 "bb8673c7fa4ee65c3c060a88328d029d4ded37fec1c34247fd9c8e3366fedc32"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4dfac90a99df3dfa493af2c7a851055833484bbfa474ad9f6662b2a07caf4a62"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c0e4a2f4fc7519e6b2eebe0ac0264486ed30eb577ccc8c667314621270d25a66"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1902d7f476f0a76dac382bc17beb0e6a3f5d06f32b58a34e455dc52d33a25cda"
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/#{version}/acloud_#{version}_linux_amd64.tar.gz"
    end
  end

  name "acloud"
  desc ""
  homepage "https://docs.avisi.cloud/docs/cli/acloud/overview/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acloud"
  bash_completion "completions/acloud.bash"
  fish_completion "completions/acloud.fish"
  zsh_completion "completions/acloud.zsh"

  # No zap stanza required
end
