# This file was generated by GoReleaser. DO NOT EDIT.
cask "acloud-toolkit" do
  name "acloud-toolkit"
  desc ""
  homepage "https://docs.avisi.cloud/docs/cli/acloud-toolkit/overview"
  version "1.18.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acloud-toolkit"
  bash_completion "completions/acloud-toolkit.bash"
  zsh_completion "completions/acloud-toolkit.zsh"
  fish_completion "completions/acloud-toolkit.fish"

  on_macos do
    on_intel do
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v#{version}/acloud-toolkit_#{version}_darwin_amd64.tar.gz"
      sha256 "34b8d3f09704edbdc78aad3e191a635bc32be6e6259ac40c9d2897665ca6a2c4"
    end
    on_arm do
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v#{version}/acloud-toolkit_#{version}_darwin_arm64.tar.gz"
      sha256 "ae92b801e26be6a2858d870045210bd031efae8b7025b1f41d4903a7ef7527ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v#{version}/acloud-toolkit_#{version}_linux_amd64.tar.gz"
      sha256 "f5debac9d00d2edd2c93dd01e344142c5ad57ee29550ba936157f5f0c56217f3"
    end
    on_arm do
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v#{version}/acloud-toolkit_#{version}_linux_arm64.tar.gz"
      sha256 "20d3053bc5d056d86016afa5b07236b7431ee5e4891e79889cd23233f3d1a703"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/acloud-toolkit"]
    end
  end

  # No zap stanza required
end
