# This file was generated by GoReleaser. DO NOT EDIT.
cask "acloud-toolkit" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/acloud-toolkit"]
    end
  end

  version "1.18.3"

  on_macos do
    on_arm do
      sha256 "310dbbf735fb12175c0c478ec668cfcb4f5b72e89ed01cda3a4910a7195b594b"
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v#{version}/acloud-toolkit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cad949af8668a7364bb75afd0156daadb3867871005ad0d4355c0fcf036a2681"
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v#{version}/acloud-toolkit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6e9a58548914b31f9d657e0f16f4dcd919a5357c08e896c3178b93dad6126a08"
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v#{version}/acloud-toolkit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c4836d4da97da5adcc4d0b070cbb883937253fbb93154cc8e8969902fc38266a"
      url "https://github.com/avisi-cloud/acloud-toolkit/releases/download/v#{version}/acloud-toolkit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "acloud-toolkit"
  desc ""
  homepage "https://docs.avisi.cloud/docs/cli/acloud-toolkit/overview"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acloud-toolkit"
  bash_completion "completions/acloud-toolkit.bash"
  fish_completion "completions/acloud-toolkit.fish"
  zsh_completion "completions/acloud-toolkit.zsh"

  # No zap stanza required
end
