# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AcloudToolkit < Formula
  desc ""
  homepage "https://docs.avisi.cloud/"
  version "1.8.2"

  depends_on "fzf" => :optional
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud-toolkit/1.8.2/acloud-toolkit_1.8.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "64d09d0dc24e6f2b740c84c74ad27796f898ba4da94144ed518e1f40e4f64182"

      def install
        bin.install "acloud-toolkit"
        zsh_completion.install "completions/acloud-toolkit.zsh" => "_acloud-toolkit"
        bash_completion.install "completions/acloud-toolkit.bash" => "acloud-toolkit"
        fish_completion.install "completions/acloud-toolkit.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud-toolkit/1.8.2/acloud-toolkit_1.8.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "72fa31effb15673e80aca99c4a26c549a16ac8743589dfa586b2c4fcb4e28aee"

      def install
        bin.install "acloud-toolkit"
        zsh_completion.install "completions/acloud-toolkit.zsh" => "_acloud-toolkit"
        bash_completion.install "completions/acloud-toolkit.bash" => "acloud-toolkit"
        fish_completion.install "completions/acloud-toolkit.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud-toolkit/1.8.2/acloud-toolkit_1.8.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "009ecb2e4e85b32b7b25803522d94218310c009ed35443fb5ad1a7583e7b5764"

      def install
        bin.install "acloud-toolkit"
        zsh_completion.install "completions/acloud-toolkit.zsh" => "_acloud-toolkit"
        bash_completion.install "completions/acloud-toolkit.bash" => "acloud-toolkit"
        fish_completion.install "completions/acloud-toolkit.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud-toolkit/1.8.2/acloud-toolkit_1.8.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "979f38dbc0ebc2b6bf61770631b6593a49a37df67904822ad633b8196f7afcb8"

      def install
        bin.install "acloud-toolkit"
        zsh_completion.install "completions/acloud-toolkit.zsh" => "_acloud-toolkit"
        bash_completion.install "completions/acloud-toolkit.bash" => "acloud-toolkit"
        fish_completion.install "completions/acloud-toolkit.fish"
      end
    end
  end

  test do
    system "#{bin}/acloud-toolkit version"
  end
end
