# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acloud < Formula
  desc ""
  homepage "https://avisi.nl/"
  version "0.23.1"

  depends_on "fzf" => :optional
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.23.1/acloud_0.23.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "56cb450d9fa6563daba9cb1decf2e13e9e36bb02b7777c38d6a45addf3e1d694"

      def install
        bin.install "acloud"
        zsh_completion.install "completions/acloud.zsh" => "_acloud"
        bash_completion.install "completions/acloud.bash" => "acloud"
        fish_completion.install "completions/acloud.fish"
      end
    end
    on_arm do
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.23.1/acloud_0.23.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c73f5dc062ea8488a60b77e467f28ae6afb9654f0ce9ade3f8e795e484302966"

      def install
        bin.install "acloud"
        zsh_completion.install "completions/acloud.zsh" => "_acloud"
        bash_completion.install "completions/acloud.bash" => "acloud"
        fish_completion.install "completions/acloud.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.23.1/acloud_0.23.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "475512fc1089803ef072677fe121b0d8f59d8ba4e6b6f93ce8f80c8ba7eb730d"

        def install
          bin.install "acloud"
          zsh_completion.install "completions/acloud.zsh" => "_acloud"
          bash_completion.install "completions/acloud.bash" => "acloud"
          fish_completion.install "completions/acloud.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.23.1/acloud_0.23.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "9b08b81e0531cf584688621621c7d414b34a69167fbcf3313c9dcac99b586a10"

        def install
          bin.install "acloud"
          zsh_completion.install "completions/acloud.zsh" => "_acloud"
          bash_completion.install "completions/acloud.bash" => "acloud"
          fish_completion.install "completions/acloud.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/acloud version"
  end
end
