# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acloud < Formula
  desc ""
  homepage "https://avisi.nl/"
  version "0.22.0"

  depends_on "fzf" => :optional
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.22.0/acloud_0.22.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "2983b90dca7f9f26b19a99abb4829373a2f88102e36bcf122d64081131883255"

      def install
        bin.install "acloud"
        zsh_completion.install "completions/acloud.zsh" => "_acloud"
        bash_completion.install "completions/acloud.bash" => "acloud"
        fish_completion.install "completions/acloud.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.22.0/acloud_0.22.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3b94676ba3df8aec2157cffa2f485e68e7e8988f869b905915905ed9ed32ac7b"

      def install
        bin.install "acloud"
        zsh_completion.install "completions/acloud.zsh" => "_acloud"
        bash_completion.install "completions/acloud.bash" => "acloud"
        fish_completion.install "completions/acloud.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.22.0/acloud_0.22.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "801289ac869fddaeaf5c5fffc31a99f602d6bf730e14840e8db90264a73cae0a"

      def install
        bin.install "acloud"
        zsh_completion.install "completions/acloud.zsh" => "_acloud"
        bash_completion.install "completions/acloud.bash" => "acloud"
        fish_completion.install "completions/acloud.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.22.0/acloud_0.22.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e481b3fd3d3fa09c30308b97f34c99bb2d68562726c15570b2c3b6f16edeb3af"

      def install
        bin.install "acloud"
        zsh_completion.install "completions/acloud.zsh" => "_acloud"
        bash_completion.install "completions/acloud.bash" => "acloud"
        fish_completion.install "completions/acloud.fish"
      end
    end
  end

  test do
    system "#{bin}/acloud version"
  end
end
