# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acloud < Formula
  desc ""
  homepage "https://avisi.nl/"
  version "0.15.1"

  depends_on "zsh" => :optional
  depends_on "fzf" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.15.1/acloud_0.15.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9e6239a07fdeb402173bfda405054f56890a7dd12810af2af55407e0ae8a1a0c"

      def install
        bin.install "acloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.15.1/acloud_0.15.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "5c4bafd249c81032d0b5e4e7c87546847e09b2a2876f85e8f4d4dc43d4081e3b"

      def install
        bin.install "acloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.15.1/acloud_0.15.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "bded334f1669c6aa1842803bc09c6d2ce54ee7cc83b3a0a687d71433e4f4f333"

      def install
        bin.install "acloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud/0.15.1/acloud_0.15.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "aa4a99588acabd565f3db590403584f7f65931e9407aaca81278355b8fcdde15"

      def install
        bin.install "acloud"
      end
    end
  end

  test do
    system "#{bin}/acloud version"
  end
end
