# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AcloudToolkit < Formula
  desc ""
  homepage "https://docs.avisi.cloud/"
  version "1.10.3"

  depends_on "fzf" => :optional
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud-toolkit/1.10.3/acloud-toolkit_1.10.3_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f0336b3a9f37dd44c62948bc9dae977598ae5a599559766b3e0bed0ce85f3ae8"

      def install
        bin.install "acloud-toolkit"
        zsh_completion.install "completions/acloud-toolkit.zsh" => "_acloud-toolkit"
        bash_completion.install "completions/acloud-toolkit.bash" => "acloud-toolkit"
        fish_completion.install "completions/acloud-toolkit.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud-toolkit/1.10.3/acloud-toolkit_1.10.3_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "46ca9b845fd7fd0b85a2bb9298a421c457012ea29edfcd5536dc500a718336fb"

      def install
        bin.install "acloud-toolkit"
        zsh_completion.install "completions/acloud-toolkit.zsh" => "_acloud-toolkit"
        bash_completion.install "completions/acloud-toolkit.bash" => "acloud-toolkit"
        fish_completion.install "completions/acloud-toolkit.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud-toolkit/1.10.3/acloud-toolkit_1.10.3_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "8604cdca0d960737c9287ca7397ad8410f2f2e547331377563dbf52edf724748"

        def install
          bin.install "acloud-toolkit"
          zsh_completion.install "completions/acloud-toolkit.zsh" => "_acloud-toolkit"
          bash_completion.install "completions/acloud-toolkit.bash" => "acloud-toolkit"
          fish_completion.install "completions/acloud-toolkit.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/acloud-toolkit/1.10.3/acloud-toolkit_1.10.3_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "2641c1bef95296033a2c9eed07f7e87fc09627d2bc489254329975c53a588de1"

        def install
          bin.install "acloud-toolkit"
          zsh_completion.install "completions/acloud-toolkit.zsh" => "_acloud-toolkit"
          bash_completion.install "completions/acloud-toolkit.bash" => "acloud-toolkit"
          fish_completion.install "completions/acloud-toolkit.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/acloud-toolkit version"
  end
end
