# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uptimectl < Formula
    desc ""
    homepage "https://docs.avisi.cloud/"
    version "0.0.2"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/uptimectl/0.0.2/uptimectl_0.0.2_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
        sha256 "71b7b15aa40e164b278c13c3609ea6c5ff532daf0eefdc40e12bd9f6166cfffa"
  
        def install
          bin.install "uptimectl"
        end
      end
      if Hardware::CPU.intel?
        url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/uptimectl/0.0.2/uptimectl_0.0.2_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
        sha256 "d6de3bddc6beacbdcdd96248b7f3ab8a3ad9f9b833052aff5ba961da4997fb11"
  
        def install
          bin.install "uptimectl"
        end
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/uptimectl/0.0.2/uptimectl_0.0.2_linux_arm64.tar.gz", :using => CurlDownloadStrategy
        sha256 "bc32ea5667731121717efb43baab1ca70b76dfd8059fc1e6e0e2c4aad6bf700c"
  
        def install
          bin.install "uptimectl"
        end
      end
      if Hardware::CPU.intel?
        url "https://avisi-cloud-brew-tap-public.s3.eu-west-1.amazonaws.com/releases/uptimectl/0.0.2/uptimectl_0.0.2_linux_amd64.tar.gz", :using => CurlDownloadStrategy
        sha256 "188e170345fe84f23276bce2eeb76c9acc831698d22c1ad054f6d992c3207a36"
  
        def install
          bin.install "uptimectl"
        end
      end
    end
  
    depends_on "zsh" => :optional
    depends_on "fnf" => :optional
  
    test do
      system "#{bin}/uptimectl version"
    end
  end
  